name: nexus
description: "A new Flutter package project."
version: 0.0.1

homepage: https://github.com/Miracle-Blue/nexus
issue_tracker: https://github.com/Miracle-Blue/nexus/issues

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  intl: ^0.20.2
  dio: ^5.8.0+1
  uuid: ^4.5.1
  html: ^0.15.5+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
