name: nexus
description: "A new Flutter package project."
version: 0.0.1

homepage: https://github.com/Miracle-Blue/nexus
issue_tracker: https://github.com/Miracle-Blue/nexus/issues

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  intl: any
  dio: any
  uuid: any
  equatable: any
  share_plus: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: any
