name: thunder
description: "Flutter network inspector for Dio client, offering real-time monitoring, detailed logs, and curl command generation for debugging."
version: 0.0.3

homepage: https://github.com/Miracle-Blue/thunder
repository: https://github.com/Miracle-Blue/thunder
issue_tracker: https://github.com/Miracle-Blue/thunder/issues

topics:
  - network
  - debugging
  - inspection
  - http
  - dio

platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  intl: any
  dio: ^5.8.0+1
  html: ^0.15.5+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
