name: nexus
description: "A new Flutter package project."
version: 0.0.1

homepage: https://github.com/Miracle-Blue/nexus
issue_tracker: https://github.com/Miracle-Blue/nexus/issues

environment:
  sdk: ^3.6.1
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
