name: thunder
description: "Flutter network inspector for Dio client, offering real-time monitoring, detailed logs, and curl command generation for debugging."
version: 0.2.2

homepage: https://github.com/Miracle-Blue/thunder
repository: https://github.com/Miracle-Blue/thunder
issue_tracker: https://github.com/Miracle-Blue/thunder/issues

topics:
  - network
  - debugging
  - inspection
  - http
  - dio

platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  intl: any
  dio: ^5.0.0
  html: any

dev_dependencies:
  flutter_test:
    sdk: flutter
